--- !ditz.rubyforge.org,2008-03-06/project 
name: nodejsbaseline
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: nodejsbaseline
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "1.0"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2016-05-20 18:03:05.974000 Z
    - Matthew Hussey <matthew.hussey@googlemail.com>
    - created
    - First release of nodejs nucleus project.
